// <auto-generated />
using System;
using Ferret.Example.Cursor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ferret.Example.Cursor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512235419_InitialFerretIndexes")]
    partial class InitialFerretIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Ferret:RequiredExtensions:v1", "[\"pg_trgm\"]")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ferret.Samples.Cursor.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasAnnotation("Ferret:SearchableIndex:v1", "{\"IndexName\":\"ix_products_name_gist_trgm\",\"TableName\":\"products\",\"ColumnName\":\"name\",\"IndexSql\":\"CREATE INDEX CONCURRENTLY IF NOT EXISTS \\u0022ix_products_name_gist_trgm\\u0022 ON \\u0022products\\u0022 USING gist ((\\u0022name\\u0022::text) gist_trgm_ops);\",\"RequiredExtensions\":[\"pg_trgm\"]}");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku")
                        .HasAnnotation("Ferret:SearchableIndex:v1", "{\"IndexName\":\"ix_products_sku_gist_trgm\",\"TableName\":\"products\",\"ColumnName\":\"sku\",\"IndexSql\":\"CREATE INDEX CONCURRENTLY IF NOT EXISTS \\u0022ix_products_sku_gist_trgm\\u0022 ON \\u0022products\\u0022 USING gist ((\\u0022sku\\u0022::text) gist_trgm_ops);\",\"RequiredExtensions\":[\"pg_trgm\"]}");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.HasKey("Id");

                    b.ToTable("products", (string)null);
                });
            modelBuilder.HasAnnotation("Ferret:RequiredExtensions:v1", """["pg_trgm"]""");
            modelBuilder.Entity("Ferret.Samples.Cursor.Product", b => b.Property<string>("Name").HasAnnotation("Ferret:SearchableIndex:v1", """{"IndexName":"ix_products_name_gist_trgm","TableName":"products","ColumnName":"name","IndexSql":"CREATE INDEX CONCURRENTLY IF NOT EXISTS \u0022ix_products_name_gist_trgm\u0022 ON \u0022products\u0022 USING gist ((\u0022name\u0022::text) gist_trgm_ops);","RequiredExtensions":["pg_trgm"]}"""));
            modelBuilder.Entity("Ferret.Samples.Cursor.Product", b => b.Property<string>("Sku").HasAnnotation("Ferret:SearchableIndex:v1", """{"IndexName":"ix_products_sku_gist_trgm","TableName":"products","ColumnName":"sku","IndexSql":"CREATE INDEX CONCURRENTLY IF NOT EXISTS \u0022ix_products_sku_gist_trgm\u0022 ON \u0022products\u0022 USING gist ((\u0022sku\u0022::text) gist_trgm_ops);","RequiredExtensions":["pg_trgm"]}"""));
#pragma warning restore 612, 618
        }
    }
}
